### PR TITLE
Hopefully this is helpful

### PR DESCRIPTION
**Pull request by rjspotter**
It's working for me thus far.  Still needs more testing.

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@rjspotter @paales Is this pull request still relevant?

**Comment by rjspotter** [comment]
@FluorescentHallucinogen I think so.  I don't see a reason why we shouldn't update to apollo2.  That said, the batch interface works for me but, might not be something we want to upstream.

**Comment by FluorescentHallucinogen** [comment]
@rjspotter But currently the `master` branch already uses Apollo 2. It seems your pull request is based on the old version of code. Could you please rebase?

**Comment by FluorescentHallucinogen** [comment]
@rjspotter Since https://github.com/reach-digital/polymer-apollo-client/commit/e1426be005e34377052aabb6095a7822b77ef23f merged, is this pull request still relevant?

**Comment by rjspotter** [comment]
No, we can close this.  
54f14ae has some code that might be useful if a person is using a backend written using Absinthe/Elixir

**Pull request closed without merging**
